;;; orgbrain-live.el --- Explicit isolated client smoke test -*- lexical-binding: t; -*-
;; Load only in a separately configured sandbox Emacs. No default endpoint.
(require 'init-orgbrain)
(require 'cl-lib)
(require 'json)

(defvar orgbrain-live-records nil)
(defun orgbrain-live-record (_label _text stdout _problem &rest _)
  (let ((record (+orgbrain--parse-json stdout)))
    (when record (push record orgbrain-live-records))))
(defun orgbrain-live-wait ()
  (let ((deadline (+ (float-time) 240)))
    (while (and +orgbrain--pending (< (float-time) deadline))
      (accept-process-output nil 0.1))
    (when +orgbrain--pending (error "Client request did not finish")))
  (when (equal (+orgbrain--dig (car orgbrain-live-records) "state") "failed")
    (error "Live job failed: %S" (+orgbrain--dig (car orgbrain-live-records) "error"))))
(defun orgbrain-live-send (mode text)
  (setq +orgbrain--mode mode)
  (+orgbrain--set-input text)
  (+orgbrain/send)
  (orgbrain-live-wait)
  (when (equal (+orgbrain--dig (car orgbrain-live-records) "result" "conversation_receipt" "answer" "status") "failed")
    (error "Memory returned but answer composition failed"))
  (unless (eq mode 'recall)
    (let ((capture (+orgbrain--dig (car orgbrain-live-records) "result" "conversation_receipt" "capture")))
      (unless (and (equal (+orgbrain--dig capture "user" "status") "verified")
                   (equal (+orgbrain--dig capture "assistant" "status") "verified"))
        (error "Conversation capture not verified: %S" capture)))))
(defun orgbrain-live-expect-memory (status)
  (unless (equal status (+orgbrain--dig (car orgbrain-live-records) "result" "memory_receipt" "status"))
    (error "Expected memory %s: %S" status (car orgbrain-live-records))))

(defun orgbrain-live-run ()
  "Exercise the real client against the explicitly supplied sandbox CLI."
  (unless (and (getenv "ORGBRAIN_LIVE_SANDBOX")
               (getenv "ORGBRAIN_LIVE_COMMAND"))
    (error "Explicit isolated sandbox configuration required"))
  (setq +orgbrain-command (getenv "ORGBRAIN_LIVE_COMMAND")
        +orgbrain-transport #'+orgbrain--transport-local
        +orgbrain-timeout 240
        +orgbrain--project "atlas"
        +orgbrain--capture-discussion nil
        orgbrain-live-records nil)
  (+orgbrain--buffer 'output)
  (+orgbrain--buffer 'input)
  (+orgbrain--probe-conversation-support)
  (unless (eq +orgbrain--conversation-support 'yes) (error "Conversation CLI unavailable"))
  (+orgbrain/new-conversation)
  (setq +orgbrain--conversation-project "atlas")
  (advice-add '+orgbrain--finish-send :before #'orgbrain-live-record)
  (unwind-protect
      (progn
        (orgbrain-live-send 'ask "Why did we keep sequential execution for deterministic replay?")
        (orgbrain-live-send 'propose "ATLAS uses deterministic replay.")
        (orgbrain-live-expect-memory "pending_confirmation")
        ;; Approval is for this synthetic sandbox candidate only.
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (+orgbrain/approve))
        (orgbrain-live-wait)
        (orgbrain-live-expect-memory "verified")
        (when +orgbrain--candidate (error "Verified candidate not cleared"))
        (+orgbrain/new-conversation)
        (orgbrain-live-send 'ask "What do we know about ATLAS and deterministic replay?")
        (orgbrain-live-send 'propose "ATLAS uses a blue review badge.")
        (orgbrain-live-expect-memory "pending_confirmation")
        (cl-letf (((symbol-function 'yes-or-no-p) (lambda (&rest _) t)))
          (+orgbrain/reject-proposal))
        (orgbrain-live-wait)
        (orgbrain-live-expect-memory "rejected")
        (when +orgbrain--candidate (error "Rejected candidate not cleared"))
        (orgbrain-live-send 'recall "ATLAS")
        (let ((+orgbrain--conversation-support 'no))
          (condition-case nil
              (progn (+orgbrain--build-propose "Never submit this." "atlas")
                     (error "Unsafe fallback was allowed"))
            (user-error nil)))
        (with-temp-file (expand-file-name "emacs-success" (getenv "ORGBRAIN_LIVE_SANDBOX"))
          (insert "All client workflow assertions passed.\n")))
    (advice-remove '+orgbrain--finish-send #'orgbrain-live-record)
    (with-temp-file (expand-file-name "emacs-records.json" (getenv "ORGBRAIN_LIVE_SANDBOX"))
      (insert (json-encode (vconcat (reverse orgbrain-live-records)))))
    (with-current-buffer (+orgbrain--buffer 'output)
      (write-region (point-min) (point-max)
                    (expand-file-name "emacs-transcript.txt" (getenv "ORGBRAIN_LIVE_SANDBOX")) nil 'silent))))

(defun orgbrain-live-repair-regression ()
  "Run the two previously failing requests through the same local client."
  (unless (getenv "ORGBRAIN_LIVE_SANDBOX") (error "Sandbox required"))
  (setq orgbrain-live-records nil)
  (advice-add '+orgbrain--finish-send :before #'orgbrain-live-record)
  (unwind-protect
      (progn
        (orgbrain-live-send 'ask "Please remember this: ATLAS uses deterministic replay. Explain the throughput trade-off and challenge the decision.")
        (orgbrain-live-send 'ask "Could you remember our previous discussion about replay?"))
    (advice-remove '+orgbrain--finish-send #'orgbrain-live-record)
    (with-temp-file (expand-file-name "emacs-repair-records.json" (getenv "ORGBRAIN_LIVE_SANDBOX"))
      (insert (json-encode (vconcat (reverse orgbrain-live-records)))))
    (with-current-buffer (+orgbrain--buffer 'output)
      (write-region (point-min) (point-max)
                    (expand-file-name "emacs-transcript.txt" (getenv "ORGBRAIN_LIVE_SANDBOX")) nil 'silent))))
